### ISSUE TITLE
Error while loading different image for testing

### ISSUE THREAD

**Issue by 16sweetyjain** [Aqsa-K/Car-Number-Plate-Detection-OpenCV-Python#8]
Traceback (most recent call last):
  File "c:/Users/hp/Documents/ObjectDetection/number-plate/Car-Number-Plate-Detection-OpenCV-Python/CarPlateDetection.py", line 9, in <module>
    image = imutils.resize(image, width=500)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by happlicious06** [comment]
i still get the error  'None Type' object has no attribute 'shape'
